apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: fingyan-ns
  labels:
    app: redis
    tier: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379 # Port the service will be available on
      targetPort: redisport # Named port from Deployment/Pod spec (or can be 6379 directly)
      protocol: TCP
  selector:
    app: redis # Selects Pods with label app=redis
    tier: cache
