import streamlit as st
from datetime import datetime, timedelta

try:
    from utils import api_client
except ImportError:
    import sys
    import os
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from utils import api_client

st.set_page_config(layout="wide", page_title="Predictive Insights")
st.title("🧠 Predictive Insights")
st.caption("Experimental AI-powered predictions for market trends. Not financial advice.")

# --- Inputs for Prediction ---
st.subheader("Get Trend Prediction")
default_symbols = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "NIFTYBEES.NS"] # From dummy model in backend
pred_symbol = st.selectbox(
    "Select Stock Symbol for Prediction:",
    options=default_symbols + ["Other"], # Allow custom input
    index=0
)
if pred_symbol == "Other":
    pred_symbol_custom = st.text_input("Enter Custom Stock Symbol (e.g., SBIN.NS):").upper()
    if pred_symbol_custom:
        pred_symbol = pred_symbol_custom

pred_horizon_days = st.slider(
    "Prediction Horizon (Days):",
    min_value=1,
    max_value=30, # Max supported by dummy model is 14, but UI can allow more
    value=7
)

# --- Fetch and Display Prediction ---
if pred_symbol and st.button(f"🔮 Predict Trend for {pred_symbol}"):
    with st.spinner(f"Generating prediction for {pred_symbol} ({pred_horizon_days} days)..."):
        prediction_data = api_client.get_trend_prediction(pred_symbol, pred_horizon_days)

    if prediction_data:
        st.markdown("---")
        st.subheader(f"Prediction for: {prediction_data['symbol']}")

        trend_info = prediction_data.get('trend')
        if trend_info:
            direction = trend_info.get('direction', 'N/A')
            confidence = trend_info.get('confidence')

            # Display with some visual cues
            if direction == "UP":
                st.metric(label=f"{prediction_data['prediction_horizon_days']}-Day Trend", value="⬆️ UP", delta=f"Confidence: {confidence*100:.1f}%" if confidence else "N/A")
            elif direction == "DOWN":
                st.metric(label=f"{prediction_data['prediction_horizon_days']}-Day Trend", value="⬇️ DOWN", delta=f"Confidence: {confidence*100:.1f}%" if confidence else "N/A", delta_color="inverse")
            elif direction == "SIDEWAYS":
                st.metric(label=f"{prediction_data['prediction_horizon_days']}-Day Trend", value="↔️ SIDEWAYS", delta=f"Confidence: {confidence*100:.1f}%" if confidence else "N/A", delta_color="off")
            else: # UNCERTAIN or other
                st.metric(label=f"{prediction_data['prediction_horizon_days']}-Day Trend", value=f"{direction}", delta="Confidence: N/A", delta_color="off")

            # st.write(f"**Direction:** {direction}")
            # if confidence is not None:
            #     st.write(f"**Confidence:** {confidence*100:.1f}%")
        else:
            st.warning("Trend prediction data not available in the response.")

        st.caption(f"Model: {prediction_data['model_name']} | Generated: {datetime.fromisoformat(prediction_data['generated_at']).strftime('%Y-%m-%d %H:%M:%S UTC')}")

        with st.expander("Raw Model Output (Debug)"):
            st.json(prediction_data.get('raw_model_output', {}))

        st.markdown(f"**Disclaimer:** {prediction_data.get('disclaimer', '')}")

    else:
        # Error is usually displayed by api_client.py via st.error()
        # Add a generic message here if nothing was displayed by client
        if not any(msg.type == "error" for msg in st.session_state.get("page_script_queue", [])): # Hacky check
             st.error("Failed to retrieve prediction. Please check the symbol and try again, or see error messages above if any.")

st.markdown("---")
st.info("""
**About Predictions:**
- These predictions are generated by experimental AI models and are for informational purposes only.
- **They do NOT constitute financial advice.** Always do your own research (DYOR) before making investment decisions.
- Model accuracy can vary, and past performance is not indicative of future results.
- The backend currently uses a placeholder model. Supported symbols and horizon might be limited.
""")

# TODO:
# - Add more types of predictions once backend supports them (e.g., price point forecasts for charts, sentiment scores).
# - Visualize time-series predictions if available.
# - Allow selection of different prediction models if backend lists them.
# - Provide more context or features that the model used, if applicable.
